---
homebrew_packages:
  - {name: autoconf}
  - {name: gifsicle}
  - {name: git}
  - {name: go}
  - {name: httpie}
  - {name: ssh-copy-id}
  - {name: cowsay}
  - {name: readline}
  - {name: openssl}
  - {name: pv}
  - {name: wget}
  - {name: sl}
  - {name: fish}
  - {name: jq}
  - {name: pyenv}
  - {name: docker-compose, state: absent}
  - {name: watch}
  - {name: peco}
  - {name: gibo}
  - {name: tree}
  - {name: pstree}

homebrew_cask_packages:
  - {name: docker}
  - {name: google-chrome}
  - {name: licecap}
  - {name: macvim}
  - {name: slack}
  - {name: transmit, state: absent}
  - {name: virtualbox}
  - {name: vagrant}
  - {name: discord}
  - {name: iterm2}
  - {name: pycharm-ce}
  - {name: cheatsheet}
  - {name: visual-studio-code}
  - {name: google-drive-file-stream}
  - {name: google-japanese-ime}
  - {name: kindle}
  - {name: steam}

fisher_packages:
  - oh-my-fish/theme-bobthefish
  - oh-my-fish/plugin-peco
  - 0rax/fish-bd
  - jethrokuan/z

vscode_extensions:
  - MS-CEINTL.vscode-language-pack-ja
  - vscode-icons-team.vscode-icons
  - ms-python.python
  - redhat.vscode-yaml
  - vscoss.vscode-ansible
  - wraith13.background-phi-colors
  - wraith13.clairvoyant
  - wraith13.zoombar-vscode
  - oderwat.indent-rainbow
  - mechatroner.rainbow-csv
  - ms-azuretools.vscode-docker
  - DavidAnson.vscode-markdownlint
  - wholroyd.jinja

git_config:
  system:
    credential.helper: osxkeychain
  global:
    user.name: あんでぃー
    user.email: bboy.answer.d@gmail.com
