---
homebrew_packages:
  - { name: autoconf }
  - { name: gifsicle }
  - { name: git }
  - { name: go }
  - { name: httpie }
  - { name: ssh-copy-id }
  - { name: cowsay }
  - { name: readline }
  - { name: openssl }
  - { name: pv }
  - { name: wget }
  - { name: sl }
  - { name: fish }
  - { name: jq }
  - { name: pyenv }

homebrew_cask_packages:
  - { name: docker }
  - { name: google-chrome }
  - { name: licecap }
  - { name: macvim }
  - { name: slack }
  - { name: transmit }
  - { name: vagrant }
  - { name: discord }
  - { name: iterm2 }
  - { name: pycharm-ce }
  - { name: cheatsheet }
  - { name: visual-studio-code }

fisher_packages:
  - oh-my-fish/theme-bobthefish
  - oh-my-fish/plugin-peco
  - 0rax/fish-bd
  - jethrokuan/z
