---
# https://qiita.com/morikooooo/items/9fd41bcd8d1ce9170301
- name: .vimrcのコピー
  copy:
    src: .vimrc
    dest: ~/
    mode: 0644

- name: .gvimrcのコピー
  copy:
    src: .gvimrc
    dest: ~/
    mode: 0644
