---
- name: setup mac os
  hosts: all

  pre_tasks:
    - name: HomeBrewのtapリポジトリ追加
      homebrew_tap:
        tap: "{{ item }}"
        state: present
      loop:
        - homebrew/cask
      tags:
        - package
    - name: HomeBrewのアップデート
      homebrew:
        update_homebrew: true
      tags:
        - package
    - name: HomeBrewパッケージのアップグレード
      homebrew:
        upgrade_all: true
      tags:
        - package

  tasks:
    - name: パッケージインストール
      import_role:
        name: homebrew
      tags:
        - package

    - name: OS設定
      import_role:
        name: osx_defaults
      tags:
        - osx

    - name: ホスト名設定
      import_role:
        name: hostname
      tags:
        - hostname

    # fish環境構築
    # Powerline環境構築
    - name: fish+powerline環境構築
      import_role:
        name: fish_powerline
      tags:
        - fish_powerline

    - name: pyenvでpythonインストール
      import_role:
        name: pyenv_init
      tags:
        - pyenv

    # vscode設定(settings.jsonとか拡張機能とか)

    # iterm2設定

