---
- name: setup mac os
  hosts: all

  pre_tasks:
    - name: HomeBrewのアップデート
      homebrew:
        update_homebrew: true
        upgrade_all: true
      # パッケージはいつ更新されるか分からないのでこのタスクは常にsuccessステータス
      changed_when: false
      tags:
        - package

  tasks:
    - name: ダウンロードしたアプリケーションの実行許可をチェック
      command: spctl --status
      register: spctl_results
      changed_when: false
      # 上記のコマンドはdisableの場合1を返すため
      failed_when: false
      check_mode: false

    - name: ダウンロードしたアプリケーションの実行許可をすべてのアプリケーションに与える
      command: spctl --master-disable
      become: true
      when: spctl_results.stdout != "assessments disabled"

    - name: パッケージインストール
      import_role:
        name: homebrew
      tags:
        - package
        - homebrew

    - name: OS設定
      import_role:
        name: osx_defaults
      tags:
        - osx_defaults

    - name: ホスト名設定
      import_role:
        name: hostname
      tags:
        - hostname

    - name: fish+powerline環境構築
      import_role:
        name: fish_powerline_install
      tags:
        - fish_powerline_install

    - name: fishコンフィグ設定
      import_role:
        name: fish_config
      tags:
        - fish_config

    - name: pyenvでpythonインストール
      import_role:
        name: pyenv_init
      tags:
        - pyenv_init

    - name: vscode設定
      import_role:
        name: vscode
      tags:
        - vscode

    - name: gitconfig
      import_role:
        name: gitconfig
      tags:
        - gitconfig

    - name: vimrc
      import_role:
        name: vimrc
      tags:
        - vimrc

    - name: nodebrew directory
      file:
        path: ~/.nodebrew/src
        state: directory
      tags:
        - nodejs
