---
dependency:
  name: galaxy
  enabled: false
driver:
  # localhostをテストインスタンスとする
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
platforms:
  - name: localhost
provisioner:
  name: ansible
verifier:
  name: ansible
