---
- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    # 設定後に再起動が必要になったためテスト除外
    # - name: ホスト名が狙ったやつになってるか
    #   assert:
    #     that: ansible_hostname == hostname
