---
- name: brewパッケージのインストール
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_packages }}"

- name: caskパッケージのインストール
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_cask_packages }}"
