---
- name: caskパッケージのインストール
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_cask_packages }}"
  # adhoc: Github ActionsのMacOS環境でインストールできないパッケージを除外するため
  when: |
    lookup("env", "ORE_NO_MACBOOK_CICD_PIPELINE") != "true" or
    (lookup("env", "ORE_NO_MACBOOK_CICD_PIPELINE") == "true" and not (item.it_skipped|default(false)))

- name: brewパッケージのインストール
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_packages }}"
