---
- name: 設定値格納用ディレクトリ作成
  file:
    path: ./osx_defaults_settings
    state: directory

# todo: ここの実装もっとかっこよくしたい…
- name: "defaults設定 - Finder"
  osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  notify:
    - restart_finder
    - output_setting
  loop: "{{ defaults.finder }}"

- name: "defaults設定 - Dock"
  osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  notify:
    - restart_dock
    - output_setting
  loop: "{{ defaults.dock }}"

- name: "defaults設定 - トラックパッド"
  osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  notify:
    - output_setting
  loop: "{{ defaults.trackpad }}"

- name: "defaults設定 - キーボード"
  osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  notify:
    - output_setting
  loop: "{{ defaults.keyboard }}"

- name: "defaults設定 - メニューバー"
  osx_defaults:
    domain: "{{ item.domain | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  notify:
    - restart_system_ui
    - output_setting
  loop: "{{ defaults.menuextra }}"

# TODO: 以下のPRによりdict型がosx_defaultsモジュールでサポートされるようになったら実装予定
# → https://github.com/ansible/ansible/pull/24808
# - name: Spotlight呼び出しショートカット変更 - 「次の入力ソースを選択」とショートカットが被るので無効化
#   osx_defaults:
#     domain: com.apple.symbolichotkeys
#     key: AppleSymbolicHotKeys
#     type: dict
#     value: |
#       61 =     {
#           enabled = 0;
#       };
#     state: present
#   notify:
#     - output_setting
#     - restart_spotlight
# - name: Spotlight呼び出しショートカット変更 - Spotlight呼び出しのショートカットキーを「option + command + space」に変更
#   osx_defaults:
#     domain: com.apple.symbolichotkeys
#     key: AppleSymbolicHotKeys
#     type: dict
#     value: |
#       64 =     {
#           enabled = 1;
#           value =         {
#               parameters =             (
#                   32,
#                   49,
#                   1572864
#               );
#               type = standard;
#           };
#       };
#     state: present
#   notify:
#     - output_setting
#     - restart_spotlight
