---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: 設定値格納用ディレクトリに今日日付のディレクトリが存在すること
      find:
        paths: ./osx_defaults_settings/
        pattern: "{{ lookup('pipe','date +%Y%m%d') }}*"
        file_type: directory
        depth: 2
      register: result_output_dir
      failed_when: not result_output_dir.matched
