---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: localhostにdelegateする実装をしているので環境チェックしてパイプライン外で動かないようにする
      assert:
        that:
          - lookup("env", "ORE_NO_MACBOOK_CICD_PIPELINE") == "true"
    - name: Install Homebrew
      shell:
        cmd: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        executable: /bin/bash
      changed_when: false
    - name: ダウンロードしたアプリケーションの実行許可をすべてのアプリケーションに与える
      command: spctl --master-disable
      become: true
      register: result_spctl_cmd
      changed_when: result_spctl_cmd.rc == 0
