---
- name: Prepare
  hosts: all
  tasks:
    - name: localhostにdelegateする実装をしているので環境チェックしてパイプライン外で動かないようにする
      assert:
        that:
          - lookup("env", "ORE_NO_MACBOOK_CICD_PIPELINE") == "true"
    - name: Install Homebrew
      shell:
        cmd: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        executable: /bin/bash
      changed_when: false
    - name: ダウンロードしたアプリケーションの実行許可をすべてのアプリケーションに与える
      command: spctl --master-disable
      become: true
      register: result
      changed_when: result.rc == 0
