---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: 狙った拡張機能がインストールされてるか
      command: code --list-extensions
      changed_when: false
      failed_when: not item in result_extension_list.stdout_lines
      register: result_extension_list
      loop: "{{ vscode_extensions }}"
