---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: localhostにdelegateする実装をしているので環境チェックしてパイプライン外で動かないようにする
      assert:
        that:
          - lookup("env", "ORE_NO_MACBOOK_CICD_PIPELINE") == "true"
    - name: テスト用にcowsayをインストールしておく
      homebrew:
        name: cowsay
