---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: slがインストールされているか
      command: /usr/bin/which sl
      changed_when: false
      register: result_sl
      failed_when: result_sl.rc != 0
    - name: cowsayがインストールされていないか
      command: /usr/bin/which cowsay
      changed_when: false
      register: result_cowsay
      failed_when: result_cowsay.rc == 0
