---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: localhostにdelegateする実装をしているので環境チェックしてパイプライン外で動かないようにする
      assert:
        that:
          - lookup("env", "ORE_NO_MACBOOK_CICD_PIPELINE") == "true"
    - name: Install Homebrew
      shell:
        cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        executable: /bin/bash
      changed_when: false
