---
- name: 使用可能なシェルの一覧にfishを追加
  lineinfile:
    path: /etc/shells
    line: /usr/local/bin/fish
    backup: yes
  become: true

- name: fishをデフォルトシェルに設定
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
  when: ansible_user_shell != "/usr/local/bin/fish"

- name: fish用ディレクトリ作成
  file:
    path: ~/.config/fish/functions/
    state: directory
    recurse: true

# Oh My FishよりFisherの方が後発、かつFisherでOMFのプラグインもインストールできるためこっちを選んだ
# → https://qiita.com/hennin/items/33758226a0de8c963ddf
- name: Fisher (fishのパッケージマネージャ)をインストール
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Fishermanのパッケージインストール状況確認
  shell:
    cmd: "fisher ls"
    executable: /usr/local/bin/fish
  changed_when: false
  check_mode: false
  register: result

- name: Fishermanでパッケージインストール
  shell:
    cmd: "fisher add {{ item }}"
    executable: /usr/local/bin/fish
  when:
    - not item in result.stdout_lines
  loop: "{{ fisher_packages }}"

- name: Powerlineフォントが既にインストールされているか確認
  find:
    paths: ~/Library/Fonts
    patterns: '*.ttf'
  register: result

- block:
  - name: PowerlineインストールのためにGitリポジトリをクローン
    git:
      repo: https://github.com/powerline/fonts.git
      dest: /tmp/powerline_fonts
      depth: 1
  - name: Powerlineフォントをインストール
    shell: /tmp/powerline_fonts/install.sh
  when: result.matched == 0

- name: Docker用のコマンド保管ファイルを配置
  get_url:
    url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/fish/docker.fish
    dest: ~/.config/fish/completions/docker.fish

- name: docker-compose用のコマンド保管ファイルを配置
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/fish/docker-compose.fish
    dest: ~/.config/fish/completions/docker-compose.fish
