---
dependency:
  name: galaxy
  enabled: false
driver:
  # localhostをテストインスタンスとする
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
platforms:
  - name: localhost
provisioner:
  name: ansible
  ansible_args:
    - "-vv"
verifier:
  name: ansible

# converge前後にcheckステップを追加してドライランが動作することをテストする
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - cleanup
    - destroy
