---
- name: Verify
  hosts: all
  tasks:
    - name: fishシェルが使用されていること
      assert:
        that:
          - ansible_user_shell == "/usr/local/bin/fish"

    - name: Fishermanが使用できること
      command: fisher -v
      changed_when: false
      failed_when: result_fisher_version.rc != 0
      register: result_fisher_version
