---
- name: Verify
  hosts: all
  tasks:
    - name: fishシェルが使用されていること
      shell: echo $SHELL
      changed_when: false
      failed_when: "'fish' not in result_shell_env.stdout"
      register: result_shell_env

    - name: Fishermanが使用できること
      command: fisher -v
      changed_when: false
      failed_when: result_fisher_version.rc != 0
      register: result_fisher_version
