---
name: CI

on: [push]

env:
  # このパイプラインで実行しない処理をスキップするための環境識別用変数
  ORE_NO_MACBOOK_CICD_PIPELINE: true

jobs:
  ut:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install molecule
        run: pip3 install -r requirements.txt
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: yamllint
        run: yamllint -s .
      - name: ansible-lint
        run: ansible-lint
      - name: markdownlint
        run: markdownlint -c .markdownlint.json .
      - name: molecule
        run: |
          base_dir=`pwd`
          for role_dir in `ls -d roles/*`
          do
            echo "=== [ $role_dir ] ==="
            cd $role_dir
            molecule test
            cd $base_dir
            echo "====================="
          done
  it:
    runs-on: macos-latest
    env:
      # ActionsのMacOSイメージはsudoパスワード無しで昇格可能
      ANSIBLE_BECOME_ASK_PASS: 0
    steps:
      - uses: actions/checkout@v2
      - name: Install homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Install Ansible
        run: brew install ansible
      - name: Dryrun check (before)
        run: ansible-playbook setup.yml -C -v
      - name: Execute setup Playbook
        run: ansible-playbook setup.yml --diff -v
      - name: Idempotence check
        run: |
          ansible-playbook setup.yml --diff -v | tee idem.log
          grep localhost idem.log | tail -1 | grep -v -e "changed=[1-9][0-9]*"
      - name: Dryrun check (after)
        run: ansible-playbook setup.yml -C -v
      - name: Integration test
        run: ansible-playbook tests/main.yml -v
