name: CI

on: [push]

jobs:
  it:
    runs-on: macos-latest
    env:
      # ActionsのMacOSイメージはsudoパスワード無しで昇格可能
      ANSIBLE_BECOME_ASK_PASS: 0
      # このパイプラインで実行しない処理をスキップするための環境識別用変数
      ORE_NO_MACBOOK_CICD_PIPELINE: true
    steps:
      - uses: actions/checkout@v2
      - name: Install homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Install Ansible
        run: brew install ansible
      - name: Execute setup Playbook
        run: ansible-playbook setup.yml --diff -v
      - name: Idempotent check
        run: |
          res=`ansible-playbook setup.yml --diff -v`
          echo $res
          echo $res | grep localhost | tail -1 | grep -v -e "changed=[1-9][0-9]*"
      - name: Dryrun check
        run: ansible-playbook setup.yml -C -v
      # TODO: AnsibleとかTestinfraでインテグレーションテスト
      # - name: Perform integrate test
      #   run: 
